package com.mgodeneche.enums;

public enum CategoriesEnum {
	AllCat("Toutes catégories"),
	EMPLOI("EMPLOI"),
	EMPLOI_offres("Offres d'emploi"),
	VEHICULES("VEHICULES"),
	VEHICULES_voiture("Voitures"),
	VEHICULES_moto("Motos"),
	VEHICULES_caravane("Caravaning"),
	VEHICULES_utilitaire("Utilitaires"),
	VEHICULES_equip_auto("Equipement Auto"),
	VEHICULES_equip_moto("Equipement Moto"),
	VEHICULES_equip_caravane("Equipement Caravaning"),
	VEHICULES_nautisme("Nautisme"),
	VEHICULES_equip_nautisme("Equipement Nautisme"),
	IMMOBILIER("IMMOBILIER"),
	IMMOBILIER_ventes("Ventes immobilières"),
	IMMOBILIER_loc("Locations"),
	IMMOBILIER_coloc("Colocations"),
	IMMOBILIER_bureaux("Bureaux &amp; Commerces"),
	VACANCES("VACANCES"),
	VACANCES_loc("Locations &amp; Gîtes"),
	VACANCES_chambre("Chambres d'hôtes"),
	VACANCES_camping("Campings"),
	VACANCES_hotel("Hôtels"),
	VACANCES_insolite("Hébergements insolites"),
	MULTIMEDIA("MULTIMEDIA"),
	MULTIMEDIA_info("Informatique"),
	MULTIMEDIA_consoles("Consoles &amp; Jeux vidéo"),
	MULTIMEDIA_image("Image &amp; Son"),
	MULTIMEDIA_tel("Téléphonie"),
	LOISIRS("LOISIRS"),
	LOISIRS_dvd("DVD / Films"),
	LOISIRS_cd("CD / Musique"),
	LOISIRS_livres("Livres"),
	LOISIRS_animaux("Animaux"),
	LOISIRS_velo("Vélos"),
	LOISIRS_sport("Sports &amp; Hobbies"),
	LOISIRS_musique("Instruments de musique"),
	LOISIRS_collection("Collection"),
	LOISIRS_jeux("Jeux &amp; Jouets"),
	LOISIRS_vins("Vins &amp; Gastronomie"),
	MATERIEL_PROFESSIONNEL("MATERIEL PROFESSIONNEL"),
	MATERIEL_PROFESSIONNEL_agricole("Matériel Agricole"),
	MATERIEL_PROFESSIONNEL_transport("Transport - Manutention"),
	MATERIEL_PROFESSIONNEL_btp("BTP - Chantier Gros-oeuvre"),
	MATERIEL_PROFESSIONNEL_outillage("Outillage - Matériaux 2nd-oeuvre"),
	MATERIEL_PROFESSIONNEL_equi_indus("Équipements Industriels"),
	MATERIEL_PROFESSIONNEL_restauration("Restauration - Hôtellerie"),
	MATERIEL_PROFESSIONNEL_fournitures("Fournitures de Bureau"),
	MATERIEL_PROFESSIONNEL_commerces("Commerces &amp; Marchés"),
	MATERIEL_PROFESSIONNEL_medical("Matériel Médical"),
	SERVICES("SERVICES"),
	SERVICES_presta("Prestations de services"),
	SERVICES_billets("Billetterie"),
	SERVICES_evenement("Evénements"),
	SERVICES_cours("Cours particuliers"),
	SERVICES_covoit("Covoiturage"),
	MAISON("MAISON"),
	MAISON_meubles("Ameublement"),
	MAISON_electro("Electroménager"),
	MAISON__table("Arts de la table"),
	MAISON_deco("Décoration"),
	MAISON__linge("Linge de maison"),
	MAISON_bricolage("Bricolage"),
	MAISON_jardinnage("Jardinage"),
	MAISON_vetements("Vêtements"),
	MAISON_chassures("Chaussures"),
	MAISON_bagagerie("Accessoires &amp; Bagagerie"),
	MAISON_bijoux("Montres &amp; Bijoux"),
	MAISON_equip_bebe("Equipement bébé"),
	MAISON_vetements_bebe("Vêtements bébé"),
	AUTRES("Autres");

	private String value = "";
	
	CategoriesEnum(String value) {
		this.value= value;
	}
}
